services:

  api_telecom:
    image: apitelecom:0.1
    container_name: telecom_ctr
    restart: always
    command: >
      python manage.py makemigrations && python manage.py migrate && gunicorn app.wsgi.application --bind 0.0.0.0:8000
    volumes:
      - api_data:/app/data
    ports:
      - "8000:8001"
volumes:
  api_data: